### PR TITLE
Add support for Umbraco 10+

### PR DESCRIPTION
**Pull request by rickbutterfield**
I pulled the repo down locally and added it to an Umbraco 10 and 11 project, and this worked for supporting both.

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @rickbutterfield and thanks for this PR 👍 

I've been debating with my self whether or not to support this package for Umbraco 10+, as it's not a package we're going to use as a company. I have some changes that I've wanted to do for a while, but haven't done so due to lack of time. So lately I've been leaning towards something similar to your PR, where there aren't any changes to the actual code base.

PR looks good, but `GridContext` would have to be registered as a singleton. As developers can add their own grid converters, a scoped lifetime isn't sufficient, as the instance has to life for the duration of the web application.

If the package is upgraded for Umbraco 10+, I'd say it should also support nullable reference types. I don't really have a good 
overview of how much this affects the package - or if the code needs to change at all. Is this something you can look into as well?

**Comment by rickbutterfield** [comment]
I've had a bit of a stab at it, turned on nullable reference types and fixed all the issues. So far I can see that all my functionality works in Umbraco 11, particularly using `GetSearchableText()`and strongly typed models/ModelsBuilder.

Next step would be to test it with Umbraco 10, which I will try and do asap.

**Comment by abjerner** [comment]
Awesome 👍 

Since release for Umbraco 10+ will be a new major version, I've created a new `v5/main` branch, and updated your PR to target that instead. That should change much - except that your changes will be merged into the correct branch.

I look forward to hear more about how your testing proceeds 😄

**Comment by rickbutterfield** [comment]
Now tested against Umbraco 10.3.2 and Umbraco 11.0.0 and can confirm that it has worked with both. I've made a minor tweak to a nullable boolean that was causing a small issue, and I've also updated the version info in the README and the `.csproj` to reflect the branch change.

**Comment by abjerner** [comment]
Hi @rickbutterfield 

I'm sorry if I sent you down a rabbit hole with the nullable references types, but unfortunately this was not what I had in mind. It seems that now everything is nullable, even though most properties and parameters are known not to be null.

I realize now that it might require some more insight into the package to do this right. In light of this, can you revert your changes back to https://github.com/skybrud/Skybrud.Umbraco.GridData/pull/41/commits/384af392c5334e8791bb748d0fe229d37c52a042? That way I can get your initial changes merged in and released on NuGet.

Enabling support for nullable reference types is not a breaking change, so I can look more into that part when I have some more time.

I hope this makes sense - and again sorry that you spent time working on the nullable support.

**Comment by rickbutterfield** [comment]
Ah sorry if I misunderstood! I simply turned on support for nullable and fixed all the issues, but it did seem like a lot of changes to make. I'll revert now.

**Comment by rickbutterfield** [comment]
Right, it's back where it was! Tested with 10.3.2 and 11.0.0 again, all working as intended.

**Comment by abjerner** [comment]
Awesome 👍 

I'll look into getting this merged and released on NuGet 😉 

Regarding enabling nullables in this package, I think in most of cases we can safely assume that certain things are not null because we know the underlying JSON structure. And we can use attributes to help the code analysis - eg. if a parameter for a method is not null, then we now the return isn't null either.

**Comment by abjerner** [comment]
[**v5.0.0-alpha001**](https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v5.0.0-alpha001) is now released on GitHub and NuGet - thanks @rickbutterfield for helping out 👍

**Pull request merged**
