### PR TITLE
Typed ModelsBuilder support; fixes #11

### LINKED ISSUE #11: ModelsBuilder generates wrong type
When I install this package in an umbraco v7.4.1 instance, ModelsBuilder generates the following field:

``` csharp
///<summary>
/// Content
///</summary>
[ImplementPropertyType("content")]
public object Content
{
    get { return this.GetPropertyValue("content"); }
}
```

This should be `GridDataModel` right?

### PR DESCRIPTION
**Pull request by gavinfaux**
Implement IPropertyValueConverterMeta interface

### CODE REVIEW

**Comment by abjerner** [comment]
Thanks for the pull request :+1: 

I haven't really used ModelsBuilder. Can you perhaps describe a bit about what the code does, or how I can test it?

**Comment by gavinfaux** [comment]
Gives a type hint to ModelsBuilder to generate a `GridDataModel` property instead of the default (which is either `object` or a `Newtonsoft.Json.Linq.JToken` depending on versions).

Just a nice to have feature when using the typed model all the time; especially with IGridConverter.

Assuming a clean install of Umbraco 7 with ModelsBuilder (7.5.0 in my case, default PureLive mode) and the Fanoe Starter Kit, before PR generates _App_Data\Models\models.generated.cs_ line 108 ...

```
[PublishedContentModel("Home")]
public partial class Home : PublishedContentModel
{
    // snipped...
    [ImplementPropertyType("content")]
    public Newtonsoft.Json.Linq.JToken Content
    {
        get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("content"); }
    }
    // snipped...
}
```

after PR

```
[PublishedContentModel("Home")]
public partial class Home : PublishedContentModel
{
    // snipped...
    [ImplementPropertyType("content")]
    public Skybrud.Umbraco.GridData.GridDataModel Content
    {
        get { return this.GetPropertyValue<Skybrud.Umbraco.GridData.GridDataModel>("content"); }
    }
    // snipped...
}
```

Can also test without PR via dropping the class in this [gist](https://gist.github.com/gavinfaux/b1d304a50b416d7f9771e270a660d308) into vanilla Umbraco web project (e.g. App_Code folder).

 A bit unsure if `GetPropertyCacheLevel` needs reviewing for `GridDataModel` or default as per [documentation](https://our.umbraco.org/documentation/extending/property-editors/value-converters-full-example-interface) will suffice.

**Comment by abjerner** [comment]
Thanks again. I'm a little busy at the moment, but I will try to find some time to have a look at it and merge your changes ;)

**Comment by abjerner** [comment]
Finally found some time to have a look st your pull request. It works fine, and your changes have now been merged. I have also pushed a [new release](https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v1.5.2) ;)

**Pull request merged**
