### PR TITLE
ReplaceEditorObjectFromConfig in v8 too

### PR DESCRIPTION
**Pull request by skttl**
#29

### CODE REVIEW

**Review by abjerner — CHANGES_REQUESTED** [review]
Hi @skttl. Thanks a lot for finding this 👍 

As the `master` branch now only targets Umbraco 8, we don't really need that check. Can you update your PR so the if statement has been removed?

**Review by abjerner — APPROVED** [review]
Awesome. Thanks for fixing 👍

**Comment by MvdDonk** [comment]
I just found out this fix also makes Umbraco preview work again. If the method "ReplaceEditorObjectFromConfig" isn't called preview mode in Umbraco isn't working either, it will result in an empty grid.

@abjerner when will this be released?

**Comment by skttl** [comment]
Great find @MvdDonk, I just had this problem too :)

**Comment by abjerner** [comment]
Sorry for the waiting time. I've now pushed a new beta release with the fix:

https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v3.0.0-beta003

Thanks again @skttl 👍

**Pull request merged**
