### PR TITLE
Update for v8.1

### PR DESCRIPTION
**Pull request by bielu**
Hi,
As I just update DTGE to 8.1 and we using Skybrud.Umbraco.GridData with that, I make the required changes to update that to 8.1.
Best,
Arkadiusz

### CODE REVIEW

**Comment by abjerner** [comment]
@bielu thanks a lot 👍

What are you reasons for adding the `riderModule.iml` file as well as the files in the `.idea` folder?

**Comment by bielu** [comment]
@abjerner  I think .ignore file for some reason doesn't update (where I exclude rider files)
I notice I add by incident only:
src/.idea/.idea.Skybrud.Umbraco.GridData/.idea/.name
instead of verything inside .idea :)

**Comment by bielu** [comment]
@abjerner Cleaned from rider, sorry for small mistake :)

**Comment by ArnoldV** [comment]
@abjerner would it be possible to release a beta2 with this fix?

**Comment by abjerner** [comment]
New beta is here: https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v3.0.0-beta002

**Comment by ArnoldV** [comment]
Thanks so much! Will let you know if we encounter any issues.

**Pull request merged**
