### PR TITLE
Create V6 version for Umbraco 13

### PR DESCRIPTION
**Pull request by skttl**
Just in case you want it - a version that works with Umbraco 13 :)

### CODE REVIEW

**Review by abjerner — CHANGES_REQUESTED** [review]
@skttl thanks 👍 

Can you make this V13 instead?

https://packages.limbo.works/versioning/

**Comment by Feliboy** [comment]
Are there any plans to for the near future to update this? I would like to update my project to Umbraco version 13 and I depend on this package.

**Comment by abjerner** [comment]
Ideally people should use the block list or block list instead, as the grid is now deprecated in Umbraco. But if you really wish to use the grid (e.g. if you've just upgraded to U13), I guess this package still has some use. I will look into pushing a new release for Umbraco 13 ;)

**Comment by abjerner** [comment]
A new [**`v13.0.0`**](https://github.com/skybrud/Skybrud.Umbraco.GridData/releases/tag/v13.0.0) release is out now 😉

**Comment by Feliboy** [comment]
Thank you! Yea I also saw the recommendation and that will also be the goal to migrate everything to the block list. But just to get everything running for now and to then move on from there, this update really helps!

**Pull request merged**
