### PR TITLE
Addition of "PropertyAlias" property to GridDataModel

### PR DESCRIPTION
**Pull request by hfloyd**
This allows a strongly-typed model using the GridDataModel to access the original property alias in order to use the default "GetGridHtml" helper in a view file.

Example:

```
@using MyCustom.Models

@inherits UmbracoViewPage<BaseModel<TextPage>>
@{
    Layout = "MasterPage.cshtml";
}

@if (Model.Content.PageContent.IsValid)
{
    @Model.Content.GetGridHtml(Model.Content.PageContent.PropertyAlias)
}
```

### CODE REVIEW

**Comment by abjerner** [comment]
Hi Heather,

Thanks for the pull request. However I'm not totally sure that I understand the purpose of adding the property alias? If `Model.Content.PageContent` is an instance of `GridDataModel`, you can already to something like:

``` C#
@Model.Content.PageContent.GetHtml(Html)
```

Would that be sufficient?

Anyways, me not understanding the purpose is probably just because we use the package a little different, so if you can describe it a little further, I have no objections to merging your changes ;)

**Comment by hfloyd** [comment]
Hi Anders, 
The main reason I didn't want to use the built in GetHtml() method was because it is looking for grid editors and frameworks in a non-default location of "~/Views/Partials/TypedGrid/". Allowing usage of the built-in GetGridHtml() method would support the standard "Grid" folder implementation.

I suppose an alternative would be to change the original source of GetHtml() to use the default folder... but my assumption was that you had changed the folder location for a reason, which I didn't want to interfere with.

**Comment by abjerner** [comment]
That makes sense. I have now merged your changes ;)

The idea with the `TypedGrid` folder was so you could keep too different implementations - eg. so that you could use the default dynamic approach for one site, and a strongly typed approach for another site - both in the same installation.

Thanks again for your help ;)

**Comment by hfloyd** [comment]
I figured that was the reason :-) I've updated the readme to help others understand how to render the grid contents... Another pull request will follow shortly.

**Comment by hfloyd** [comment]
Hi Anders, 
I noticed that in the 1.5.0 release the "PropertyAlias" property seems to be missing. Was that by design?
Thanks, 
Heather

**Comment by abjerner** [comment]
Hi Heather,

`v1.5.0` was released prior to this pull request, so that is the reason. While your help is very much appreciated, I just haven't had the time to push out a new release. I will see if I can manage do that soon ;)

**Comment by hfloyd** [comment]
Ah! No worries - I hadn't realized the order of events there :-) 

It's not an emergency for me... I just updated my local code and recompiled for my own use. It just means I can't use the NuGet package :-)

Have a great day!

**Pull request merged**
